name: base_flutter
description: A Flutter structure application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations:
  freezed_annotation:
  retrofit: ^2.0.0-beta1
  system_info:
  meta:
  equatable:
  event_bus:
  provider:
  shared_preferences:
  rxdart: ^0.26.0
  intl:
  bloc:
  validations:
  flutter_screenutil: ^5.3.1
  flutter_bloc:
  dio: ^4.0.0-prev3
  statsfl: ^2.0.1-nullsafety
  darq: ^1.0.0-dev.3
  sized_context: ^1.0.0-nullsafety
  intl_phone_field: ^3.0.0
  local_auth: ^1.1.11
  intl_phone_number_input: ^0.7.0+2
  flutter_svg:
  cached_network_image:

  xdg_directories:
  bitsdojo_window:
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 040f36c82b63e8764ec2fd97066767503a667b6d

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  extended_image: ^5.1.0
  card_swiper: ^1.0.4
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.9
  path_provider:
  path:
  camera:
  loader_overlay: ^2.0.2+1
  fluttertoast: ^8.0.8
  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9
  firebase_auth: ^3.1.4
  geolocator: ^7.7.1
  pin_code_fields: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  retrofit_generator: ^2.0.0+1
  json_serializable:
dependency_overrides:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langs/
    - assets/langs/en.json
    - assets/images/
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Hiragino Kaku Gothic Pro
      fonts:
        - asset: assets/fonts/ヒラギノ角ゴ Pro W3.otf
          weight: 400
        - asset: assets/fonts/ヒラギノ角ゴ Pro W6.otf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
